### ISSUE TITLE
Feature request: be able to hide the left side bar

### ISSUE THREAD

**Issue by Shanghi** [brisqapp/issue-tracker#10]
That's quite a lot of empty space if you're only using one board.

**Comment by ashgrover** [comment]
Yes, I've gotten this request from other users as well and this feature will get there eventually.

My plan is not to completely hide it but instead minimize it so that it shows only icons in a compact form instead of full names of the boards. This way it will also allows for quick access to other boards.

**Comment by ashgrover** [comment]
v0.5.0 now supports expanding and collapsing the side bar.
