### ISSUE TITLE
Feature request: add creation and closing date

### ISSUE THREAD

**Issue by el3um4s** [brisqapp/issue-tracker#13]
I would like to have a field where to add the creation and closing date of a task

**Comment by ashgrover** [comment]
Hi @el3um4s 

I do plan to add 'Due Date' field in the future release as mentioned in the roadmap. 

Usually, a Kanban workflow does not really have start date and completion date, but I can see the need of creation date of a task to see when the card entered the board.

Following Kanban workflow, what I do is break my tasks into small units which I can finish in half a day to full day. When I'm working on a task, I just move it to 'In Progress' list, since I know I can finish it in a day I don't really need start date and end date. However, I can see the need of a 'Due Date' here since I want to make sure I'm done with certain tasks before that due date. This removes the burden of keeping track of start and end dates.

I'll think more about the best way to approach this following the spirit of Kanban after I'm done implementing Due Dates feature.

Thanks for the suggestion.

Ash

**Comment by ashgrover** [comment]
v0.5.0 now supports Due date feature.
