### ISSUE TITLE
option to have "copy board" include cards and their content

### ISSUE THREAD

**Issue by ckhalleran** [brisqapp/issue-tracker#35]
When you copy a board, Brisqi tells you only lists and labels will be copied. Would it be possible to have it also include all the cards (and whatever  is on those cards?)

I was thinking about using this for a checklist for PCB layout work. I could have a Brisqi board for my template... copy and paste that as a new board (when I start in on a new PCB layout).

I meant to say, as an option (include cards and stuff) not as default.

**Comment by ckhalleran** [comment]
Maybe if I had a backup of just the template board, and had a way to import that backup as a new board (but without deleting my existing boards). Not sure if that would be useful or not.

**Comment by ashgrover** [comment]
@ckhalleran Thanks for the suggestion. With Brisqi I always try to avoid operations which involve dealing with large amounts of data per action, I prefer "one operation/one action" wherever possible for performance reasons, especially for operations performed when data needs to be synced to cloud. This is because Brisqi is an offline-first app, if it was online-only I wouldn't have to think about all of this that much :)
That being said, I know that deleting a board is also an operation which handles lots of data but that is just a simple operation where it just takes all the records and deletes them. I'll look into copying of cards more, see how it performs and probably provide it as an option.

Thanks again.
Ash

**Comment by DebDak** [comment]
Hello Ash - I have a number of use cases that could be enabled with a complete copy of the board ... not just the framework.  For instance when I set up a process flow I often need to use the same steps each week.  If all the cards could be copied then I could just start with a clean slate each week.  This would also give me a "history" from the previous copies of the results of past weeks.  I definitely have a second vote for a complete copy of the board!  Thanks for the great work.

**Comment by ashgrover** [comment]
Thanks for the feedback @DebDak and explaining your use case. I've added this feature request in my backlog and will be implemented in one of the future versions :)

**Comment by ashgrover** [comment]
This feature is now implemented in v0.9.0.
