### ISSUE TITLE
Unable to restore data

### ISSUE THREAD

**Issue by Urbansurvival** [brisqapp/issue-tracker#45]
Was having an issue with win11.
Made backup of Brisqi in ver 10.
reloaded win11 (corrected the excel issue)
reloaded Brisqi with ver 11
signed in and launched
Tried to recover saved back up
No joy
Any ideas?>

**Comment by Urbansurvival** [comment]
PS Says recovered but no data is restored I can see

**Comment by ashgrover** [comment]
@Urbansurvival 

Odd. v.0.11.0 doesn't have any major changes with regards to backup or restore, so it shouldn't affect the restoring ability. 

Let's try to get to the bottom of this:
1. Check the selected location of the backup file. You can do that by going to Settings -> Backup -> Change Backup Location.
2. Now copy your backup file again in that backup location.
3. Try restoring the boards again by going to Backup -> Restore Data.

Let me know if that fixes the issue.

If not, usually there's a "Backup" folder at location - "%AppData%\Brisqi\backup.brisqi"  with last 5 backups, but if you wiped out Win11 and reinstalled it again, it might have been deleted as well. But, just in-case, can you check if you still have the data there?


Thanks

**Comment by Urbansurvival** [comment]
Hi Ash – sorry to intrude into the weekend

 

They all have a similar file (and from before the win11 time stamp) but there doesn’t seem to be anything in any of them.

 

Just the empty folders.

 

I get the green “restored successfully” but there is nothing new shown on the screen – e.g. all my boards are gone…

 

G

**Comment by ashgrover** [comment]
I was just reading your first comment again. You mentioned  that you "Made backup of Brisqi in ver 10."  

How did you make a backup? Did you copy the directory where Brisqi was actually installed? I'm asking this because all of the Brisqi data is stored in location - "%AppData%\Brisqi\" and not the installation directory. Unfortunately, if you didn't make a backup of the %AppData%\Brisqi\" or even the backup.brisqi file in that AppData directory, then I'm afraid you might have lost your data.

**Comment by Urbansurvival** [comment]
The backup (in Bri.10) was done using the backup button on the settings menu…

**Comment by ashgrover** [comment]
@Urbansurvival
Please let me know if you encounter this issue again.
Closing this issue for now.
