### ISSUE TITLE
Can't Reset Application

### ISSUE THREAD

**Issue by SeanTClayton** [brisqapp/issue-tracker#64]
I just downloaded Brisqi. I made some changes, including accidentally deleting a couple labels. I have the free version, so it wouldn't let me make more labels, even though I started off with more than I have now. I tried to uninstall and re-install the application, but it keeps all the changes I made. I keep trying to delete all associated files and registry keys to no avail. I cannot undo the changes I made. It is ridiculously persistent.

**Comment by ashgrover** [comment]
Hi,
Thanks for reaching out. In the free version of Brisqi, the limit is five labels, as noted on the [website](https://brisqi.com/pricing). The labels you saw initially are part of the sample board, which is designed to help users get familiar with the interface. If you delete any labels from that sample board, you won't be able to create new ones because of the five-label limit. However, to reset the application, you can try removing data from %AppData%\Brisqi directory.

If you need more flexibility with labels, you might want to consider one of our paid plans, which allow for unlimited labels. 

Let me know if you have any more questions.


Best,
Ash

**Comment by ashgrover** [comment]
Closing this issue for now. Just reach out if you have any more questions.
Thanks.
