### ISSUE TITLE
How to choose where to save the boards?

### ISSUE THREAD

**Issue by el3um4s** [brisqapp/issue-tracker#7]
I saw that the backup (#3)  is saved here:

> On Windows - %AppData%\Brisqi\backup.brisqi
> On Linux(Ubuntu) - /home/user/.config/Brisqi/backup.brisqi

But where are the "normal" files saved?

I would like to have a copy of my boards on a USB device so that I can consult them both at home and in the office.

**Comment by ashgrover** [comment]
Hi @el3um4s,

Brisqi stores its data in a local database and not in individual files. The backup file is an export of that database in a json format.

You can copy that backup file onto your USB and import it on another device. Otherwise, there's always an option of syncing your boards to cloud then you can access your boards from anywhere.

I had made the decision of storing data in a database due to various reasons. Local database gives better performance compared to files when reading/writing data. Keeping track of changes made to the boards in a database for synchronization purposes is easier and more reliable than a file. And, in general, a database is more fault tolerant and reliable.

Regards,
Ash

**Comment by el3um4s** [comment]
Thank you for your response

**Comment by ashgrover** [comment]
No problem!
