### ISSUE TITLE
Feature request: show subtask checklists on cards

### ISSUE THREAD

**Issue by Shanghi** [brisqapp/issue-tracker#9]
The checklist (probably a simplified one without the ability to sort/delete tasks) would be very convenient to see and use in the main card view, and it kind of feels wrong to hide tasks even if they are just pesky subtasks. Maybe it could be optional to show in case some people feel like it might be dreadful clutter.

**Comment by ashgrover** [comment]
Thanks for the feature request.

If you have subtasks in a card, then it does show unchecked/total-subtasks (ex. 1/5) in the card view, so that would be an indicator that the card has subtasks. 

I want to keep card view as simple as possible showing the title and the tags clearly.  You might've noticed that the card subtasks and comments info are also slightly greyed out which is also intentional as I want to put more focus on the title.
Accessing subtasks is one click away so I feel putting more information in card view would take focus away from the purpose of the card view which is to give you an idea at a glance what the card is about.

I want to keep the UI clean as I feel it already shows enough information so at this time I do not plan to support this feature. However, I'm open to discussion if there is enough demand for it from more users.

Thanks again,
Ash

**Comment by ashgrover** [comment]
This feature is not available in version 0.13.0!
Closing this issue.
